# Generated by Django 6.0.2 on 2026-02-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_author_autor_rename_category_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
